DROP TABLE IF EXISTS post;
DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(50) UNIQUE NOT NULL,
  password VARCHAR(256) NOT NULL,
  picture_filename TEXT
);

CREATE TABLE post (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  author_id INT(6) UNSIGNED NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  title VARCHAR(150) NOT NULL,
  body VARCHAR(500) NOT NULL,
  FOREIGN KEY (author_id) REFERENCES user (id)
);
